# @package _global_
defaults:
  - /train-local-defaults
  - override /model: best
  - override /trainer: best

experiment: ablation-kd-best
base_path: /home/jacopo/PycharmProjects/progetto-tesi/
teacher_weights_path: ${base_path}main/dependencies/VATE/best_model_contrastive.pt

trainer:
  use_kd: False