defaults:
  - tuning-local

study_name: hp-final-proxy-fixed
search_space:
  batch_size: [ 32, 64, 128 ]

watch_configurations:
  - lr: 0.0003
    batch_size: 64
    attn_layers: 4
    beta: 0.5
  - lr: 0.0003
    batch_size: 64
    attn_layers: 4
    beta: 0.5
  - lr: 0.001
    batch_size: 64
    attn_layers: 4
    beta: 1.0