defaults:
  - tuning

study_name: hp-refine-moco-less-txt-less
watch_configurations:
  # Configuration that was best prior ablations
  - lr: 0.0003
    batch_size: 32
    attn_layers: 6
    beta: 0.5
  # Best candidate
  - lr: 0.0003
    batch_size: 32
    attn_layers: 2
    beta: 0.5
  - lr: 0.0003
    batch_size: 32
    attn_layers: 2
    beta: 2.0
  - lr: 0.0003
    batch_size: 32
    attn_layers: 2
    beta: 1.0
  - lr: 0.001
    batch_size: 32
    attn_layers: 6
    beta: 2.0
  - lr: 0.0003
    batch_size: 32
    attn_layers: 4
    beta: 0.5