base_path: /home/jacopo/PycharmProjects/progetto-tesi/data/
eeg_model_weights_path: /root/PycharmProjects/progetto-tesi/main/dependencies/cbramod/pretrained_weights.pth

defaults:
  - default
  - dataset:
      - amigos
      - mahnob
      - eav
  - target_model:
      - eegavi
      - vate
