defaults:
  - model: default
  - trainer: default
  - teacher: default
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

base_path: /root/PycharmProjects/progetto-tesi/
teacher_weights_path: ${base_path}main/dependencies/VATE/best_model_contrastive.pt


dataset_descriptors:
  - dataset_path: "/localssd/EEGAVI/AMIGOS/combined/"
    cache_path: null
    dataset_weight: 1.0
  - dataset_path: "/localssd/EEGAVI/DEAP/combined/"
    cache_path: null
    dataset_weight: 1.0


hydra:
  job_logging:
    root:
      handlers: [ console, file ]   # make sure both are used

    handlers:
      file:
        class: logging.FileHandler
        formatter: simple         # or "colorlog" if you really want ANSI codes in file
        filename: ${hydra.runtime.output_dir}/job.log