defaults:
  - model: default
  - trainer: default
  - teacher: default
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

base_path: /root/PycharmProjects/progetto-tesi/
teacher_weights_path: ${base_path}main/dependencies/VATE/best_model_contrastive.pt

student_dataset_path:
  - dataset_spec_file: "/localssd/EEGAVI/AMIGOS/interleaved_quantized/spec.csv"
    cache_path: null
  - dataset_spec_file: "/localssd/EEGAVI/DEAP/interleaved_quantized/spec.csv"
    cache_path: null
  - dataset_spec_file: "/localssd/EEGAVI/MANHOB/interleaved_quantized/spec.csv"
    cache_path: null
  - dataset_spec_file: "/mnt/turing-datasets/EEGAVI/EAV/interleaved_quantized/spec.csv"
    cache_path: "/localssd/EEGAVI/EAV/interleaved_quantized/"

teacher_dataset_path:
  - dataset_spec_file: "/localssd/EEGAVI/AMIGOS/vate_quantized/spec.csv"
    cache_path: null
  - dataset_spec_file: "/localssd/EEGAVI/DEAP/vate_quantized/spec.csv"
    cache_path: null
  - dataset_spec_file: "/localssd/EEGAVI/MANHOB/vate_quantized/spec.csv"
    cache_path: null
  - dataset_spec_file: "/mnt/turing-datasets/EEGAVI/EAV/vate_quantized/spec.csv"
    cache_path: "/localssd/EEGAVI/EAV/vate_quantized/"

hydra:
  job_logging:
    root:
      handlers: [ console, file ]   # make sure both are used

    handlers:
      file:
        class: logging.FileHandler
        formatter: simple         # or "colorlog" if you really want ANSI codes in file
        filename: ${hydra.runtime.output_dir}/job.log