defaults:
  - model: default
  - trainer: default
  - teacher: default

base_path: /home/jacopo/PycharmProjects/progetto-tesi/
teacher_weights_path: ${base_path}main/dependencies/VATE/best_model_contrastive.pt

student_dataset_path: [
  "${base_path}data/EEGAVI/AMIGOS/interleaved/spec.csv",
  "${base_path}data/EEGAVI/EAV/interleaved/spec.csv"
]
teacher_dataset_path: [
  "${base_path}data/EEGAVI/AMIGOS/vate/spec.csv",
  "${base_path}data/EEGAVI/EAV/vate/spec.csv"
]


hydra:
  job_logging:
    root:
      handlers: [ console, file ]   # make sure both are used

    handlers:
      file:
        class: logging.FileHandler
        formatter: simple         # or "colorlog" if you really want ANSI codes in file
        filename: ${hydra.runtime.output_dir}/job.log