base_path: /home/jacopo/PycharmProjects/progetto-tesi/
use_base_path: True
batch_size: 24
teacher_weights_path: main/dependencies/VATE/best_model_contrastive.pt
student_dataset_path: [
  "data/amigos/p-interleaved-d/spec.csv",
  # "data/deap/p-interleaved-d/spec.csv"
]
teacher_dataset_path: [
  "data/amigos/vate/spec.csv",
  # "data/deap/vate/spec.csv"
]
# Training infos
lr: 1e-4
kd_loss_weight: 1.0
fusion_loss_weight: 1.0
weakly_supervised_weight: 0.5
ecg_correction_weight: 0.2
kd_temperature: 0.05
epochs: 10