# @package preprocessing
dataset_name: ???
out_folder_name: ???

DatasetName: "${capitalize:${.dataset_name}}"
DATASETNAME: "${uppercase:${.dataset_name}}"

config_classpath: main.dataset.${.dataset_name}.config.${.DatasetName}Config
loader_classpath: main.dataset.${.dataset_name}.loader.${.DatasetName}PointsLoader

base_path: /mnt/turing-datasets/
# Where the dataset is placed
data_path: ${.base_path}${.DATASETNAME}/
# Where extracted intervals are placed
extraction_data_folder: ${.base_path}EEGAVI/${.DATASETNAME}/extraction-data/
# Where output has to go to
output_path: ${.base_path}EEGAVI/${.DATASETNAME}/${.out_folder_name}/
# Objects have to be defined
uid_store_path: ${.base_path}/EEGAVI/uid_store.csv

output_max_length: 32
vid_config:
  max_frames: 32

aud_config:
  fs: 16000

eeg_config:
  fs: 200
  model_weights_path: /root/PycharmProjects/progetto-tesi/main/dependencies/cbramod/pretrained_weights.pth

txt_config:
  # TODO Problema
  extracted_base_path: ${..base_path}/data/amigos/extraction_data/

ecg_config:
  fs: 128
  fm_endpoint: localhost:7860/extract_features
