# @package preprocessing
---
defaults:
  - local

dataset_name: manhob
out_folder_name: interleaved
preprocessing_pipeline: main.dataset.${.dataset_name}.preprocessing.interleaved_preprocessor

# Override different setups if needed here.