base_path: /mnt/turing-datasets/
defaults:
  - default
  - dataset: ???
  - target_model: ???

dataset:
  eeg_config:
    model_weights_path: /root/PycharmProjects/progetto-tesi/main/dependencies/cbramod/pretrained_weights.pth