# Training infos
lr: 3e-4
kd_loss_weight: 1.0
fusion_loss_weight: 1.0
kd_temperature: 0.2
epochs: 1
batch_size: 64
batches_per_epoch: 1000 # 0.6 of all.
dl_start_index: 0
ckpt_path: null
use_moco: False