student_spec_path: "/home/jacopo/dataset/EEGAVI/AMIGOS/interleaved_quantized/spec.csv"
teacher_spec_path: "//home/jacopo/dataset/EEGAVI/AMIGOS/vate_quantized/spec.csv"
output_path: "/home/jacopo/dataset/EEGAVI/AMIGOS-compressed/"